backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "assets/images/blog"
logo_url: "/assets/images/collaboration_map.png"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    extension: 'md'
    format: 'yaml-frontmatter' # It should automatically figure these out, but
      # I'll set them to be safe

    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Summary", name: "description", widget: "text", required:
        false, hint: 'Displayed in italics at the top of the post. Can just be your name.'}
      - {label: "Image", name: "image", widget: "file", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "event"
    label: "Event"
    folder: "_events"
    extension: 'md'
    format: 'yaml-frontmatter'
    sort: "date:desc"
    create: true
    delete: true # Allow users to delete items
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Link to", name: "link", widget: "string", required: false,
        hint: 'everything after https://lisec-tech.com'}
      - {label: "Description", name: "body", widget: "string", required: false,
        hint: 'currently not used, but could be in the future.'}
